package com.example.blesdktest.smartwatch

import com.veepoo.protocol.model.datas.*
import com.veepoo.protocol.model.enums.ECameraStatus


interface IBleSdkCallback {
    //    fun onConnectDevice(mac: String, deviceName: String)
//    fun onConfirmPwd(writeResponse: FiturTest.WriteResponse)
//    fun onSyncPersonInfo(writeResponse: FiturTest.WriteResponse)
    fun onHeartDataChange(heartData: HeartData)
    fun onTmpDataChange(tmpDetectData: TemptureDetectData)
    fun onVerificationpwData(pwdData: PwdData)
    fun onVerificationFuntionSupport(functionDeviceSupportData: FunctionDeviceSupportData)
    fun onSyncProfile()
    fun onSportDataChange(sportData: SportData)
    fun onResponse(state: Int)
    fun onWeatherDataChange(weatherStatusData: WeatherStatusData)
    fun onUpdateAGPS(bigTranType: Int, isSupportAgps: Boolean)
    fun onLowerPowerDataDataChange(lowPowerData: LowPowerData)
    fun onDataChange(bpFunctionData: BpFunctionData)

    //listenDeviceCallback
    fun inPttModel()
    fun outPttModel()
    fun rejectPhone()
    fun cliencePhone()
    fun knocktify()
    fun sos()
    fun nextMusic()
    fun prevMusic()
    fun pauseAndPlayMusic()
    fun pauseMusic()
    fun playMusic()
    fun voiceUp()
    fun voiceDown()
    fun operateMusicSuccess()
    fun oprateMusicFail()

    fun onDataChange(bpData: BpData)
    fun onDataChange(bpDataSettingData: BpSettingData)
    fun onCameraDataChange(oprateStatus: ECameraStatus)
    fun onAlarmDataChangeListener(alarmData: AlarmData)
    fun onDataChange(batteryData: BatteryData)
    fun onCheckWearDataChange(checkWearData: CheckWearData)
    fun onFindDevice(findDeviceData: FindDeviceData)
    fun onHeartWaringDataChange(heartWaringData: HeartWaringData)
    fun onSpO2HADataChange(spo2hData: Spo2hData)
    fun onGreenLightDataChange(data: IntArray)
    fun onAllSetDataChangeListener(allSetData: AllSetData)
    fun onSportModelStateChange(sportModelStateData: SportModelStateData)
    fun onSportStopped()
    fun onReadOriginProgress(progress: Float)
    fun onReadOriginProgressDetail(day: Int, date: String, allPackage: Int, currentPackage: Int)
    fun onHeadChangeListListener(sportModelHeadData: SportModelOriginHeadData)
    fun onItemChangeListListener(sportModelItemData: List<SportModelOriginItemData>)
    fun onReadOriginComplete()
    fun onSpo2hOriginListener(sportOriginData: Spo2hOriginData)
    fun onFatigueDataListener(fatigueData: FatigueData)
    fun onWomenDataChange(womenData: WomenData)
    fun onChantingDataChange(chantingData: ChantingData)
    fun onTemptureDataListDataChange(temptureDataList: List<TemptureData>)
    fun onSleepDataChange(day: String, sleepData: SleepData)
    fun onSleepProgress(progress: Float)
    fun onSleepProgressDetail(day: String, packagenumber: Int)
    fun onReadSleepComplete()
    fun onDrinkDataChange(packagenumber: Int, drinkdata: DrinkData)
    fun onReadDrinkComplete()
//    fun onPwdDataChange(pwd: PwdData)
//    fun onStartDetectHeart()


}